{{ $zimVersion := "1.12.1" }}
[".zim/zimfw.zsh"]
type = "file"
url = "https://github.com/zimfw/zimfw/releases/download/v{{ $zimVersion }}/zimfw.zsh"
refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" }}

{{ $pueueVersion := "3.3.3" }}
[".local/bin/pueue"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueueVersion }}/pueue-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $pueuedVersion := "3.3.3" }}
[".local/bin/pueued"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueuedVersion }}/pueued-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $moldVersion := "2.4.1" }}
[".local/bin/mold"]
type = "archive-file"
url = "https://github.com/rui314/mold/releases/download/v{{ $moldVersion }}/mold-{{ $moldVersion }}-x86_64-linux.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "bin/mold"

{{ $helixVersion := "23.05" }}
[".local/bin/hx"]
type = "archive-file"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 1
path = "hx"
[".config/helix/runtime"]
type = "archive"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 2
include = ["*/runtime/**"]

{{ $bazeliskVersion := "1.18.0" }}
[".local/bin/bazel"]
type = "file"
url = "https://github.com/bazelbuild/bazelisk/releases/download/v{{ $bazeliskVersion }}/bazelisk-linux-amd64"
refreshPeriod = "168h"
executable = true

{{ $aspectVersion := "5.8.5" }}
[".local/bin/aspect"]
type = "file"
url = "https://github.com/aspect-build/aspect-cli/releases/download/{{ $aspectVersion }}/aspect-linux_amd64"
refreshPeriod = "168h"
executable = true

# https://github.com/bazelbuild/buildtools/releases/download/v6.3.3/buildifier-linux-amd64
{{ $buildifierVersion := "6.3.3" }}
[".local/bin/buildifier"]
type = "file"
url = "https://github.com/bazelbuild/buildtools/releases/download/v{{ $buildifierVersion }}/buildifier-linux-amd64"
refreshPeriod = "168h"
executable = true

{{ $qvVersion := "0.8.4" }}
[".local/bin/qv"]
type = "archive-file"
url = "https://github.com/timvw/qv/releases/download/v{{ $qvVersion }}/qv-{{ $qvVersion }}-x86_64-unknown-linux-gnu-generic.tar.gz"
refreshPeriod = "168h"
path = "qv"

{{ end }}
