{{ if eq .chezmoi.os "linux" }}
{{ $lsdVersion := "0.23.1" }}
["local/bin/lsd"]
type = "file"
url = "https://github.com/Peltoche/lsd/releases/download/{{ $lsdVersion }}/lsd-{{ $lsdVersion }}-i686-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
executable = true
["local/bin/lsd".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lsd-{{ $lsdVersion }}-i686-unknown-linux-musl/lsd"]

{{ $nvimVersion := "0.8.0" }}
["local/bin/nvim"]
type = "file"
url = "https://github.com/neovim/neovim/releases/download/v{{ $nvimVersion }}/nvim-linux64.tar.gz"
refreshPeriod = "168h"
executable = true
["local/bin/nvim".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "nvim-linux64/bin/nvim"]
{{ end }}

[".fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf"
refreshPeriod = "168h"
[".fzf".clone]
args = ["--depth", "1"]
