{{ if eq .chezmoi.os "linux" }}

{{ $pueueVersion := "3.2.0" }}
[".local/bin/pueue"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueueVersion }}/pueue-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $pueuedVersion := "3.2.0" }}
[".local/bin/pueued"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueuedVersion }}/pueued-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $moldVersion := "2.0.0" }}
[".local/bin/mold"]
type = "archive-file"
url = "https://github.com/rui314/mold/releases/download/v{{ $moldVersion }}/mold-{{ $moldVersion }}-x86_64-linux.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "bin/mold"

{{ $jjVersion := "0.8.0" }}
[".local/bin/jj"]
type = "archive-file"
url = "https://github.com/martinvonz/jj/releases/download/v{{ $jjVersion }}/jj-v{{ $jjVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
path = "./jj"

{{ $zimVersion := "1.12.0" }}
[".zim/zimfw.zsh"]
type = "file"
url = "https://github.com/zimfw/zimfw/releases/download/v{{ $zimVersion }}/zimfw.zsh"
refreshPeriod = "168h"

{{ $helixVersion := "23.05" }}
[".local/bin/hx"]
type = "archive-file"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 1
path = "hx"
[".config/helix/runtime"]
type = "archive"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 2
include = ["*/runtime/**"]

{{ $bazeliskVersion := "1.18.0" }}
[".local/bin/bazel"]
type = "file"
url = "https://github.com/bazelbuild/bazelisk/releases/download/v{{ $bazeliskVersion }}/bazelisk-linux-amd64"
refreshPeriod = "168h"
executable = true

{{ $aspectVersion := "5.8.0" }}
[".local/bin/aspect"]
type = "file"
url = "https://github.com/aspect-build/aspect-cli/releases/download/{{ $aspectVersion }}/aspect-linux_amd64"
refreshPeriod = "168h"
executable = true

{{ end }}
