{{ if eq .chezmoi.os "linux" }}
{{ $lsdVersion := "0.23.1" }}
[".local/bin/lsd"]
type = "archive-file"
url = "https://github.com/Peltoche/lsd/releases/download/{{ $lsdVersion }}/lsd-{{ $lsdVersion }}-i686-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "lsd"

{{ $ghqVersion := "1.4.2" }}
[".local/bin/ghq"]
type = "archive-file"
url = "https://github.com/x-motemen/ghq/releases/download/v{{ $ghqVersion }}/ghq_linux_amd64.zip"
refreshPeriod = "168h"
stripComponents = 1
path = "ghq"

{{ $gitTownVersion := "9.0.0" }}
[".local/bin/git-town"]
type = "archive-file"
url = "https://github.com/git-town/git-town/releases/download/v{{ $gitTownVersion }}/git-town_{{ $gitTownVersion }}_linux_intel_64.tar.gz"
refreshPeriod = "168h"
path = "git-town"

{{ $justVersion := "1.14.0" }}
[".local/bin/just"]
type = "archive-file"
url = "https://github.com/casey/just/releases/download/{{ $justVersion }}/just-{{ $justVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
path = "just"

{{ $ghVersion := "2.32.0" }}
[".local/bin/gh"]
type = "archive-file"
url = "https://github.com/cli/cli/releases/download/v{{ $ghVersion }}/gh_{{ $ghVersion }}_linux_amd64.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "bin/gh"

{{ $shellcheckVersion := "0.9.0" }}
[".local/bin/shellcheck"]
type = "archive-file"
url = "https://github.com/koalaman/shellcheck/releases/download/v{{ $shellcheckVersion }}/shellcheck-v{{ $shellcheckVersion }}.linux.x86_64.tar.xz"
refreshPeriod = "168h"
stripComponents = 1
path = "shellcheck"

{{ $batVersion := "0.23.0" }}
[".local/bin/bat"]
type = "archive-file"
url = "https://github.com/sharkdp/bat/releases/download/v{{ $batVersion }}/bat-v{{ $batVersion }}-x86_64-unknown-linux-gnu.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "bat"

{{ $fdVersion := "8.7.0" }}
[".local/bin/fd"]
type = "archive-file"
url = "https://github.com/sharkdp/fd/releases/download/v{{ $fdVersion }}/fd-v{{ $fdVersion }}-x86_64-unknown-linux-gnu.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "fd"

{{ $rgVersion := "13.0.0" }}
[".local/bin/rg"]
type = "archive-file"
url = "https://github.com/BurntSushi/ripgrep/releases/download/{{ $rgVersion }}/ripgrep-{{ $rgVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "rg"

{{ $hyperfineVersion := "1.17.0" }}
[".local/bin/hyperfine"]
type = "archive-file"
url = "https://github.com/sharkdp/hyperfine/releases/download/v{{ $hyperfineVersion }}/hyperfine-v{{ $hyperfineVersion }}-x86_64-unknown-linux-gnu.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "hyperfine"

{{ $jqVersion := "1.6" }}
[".local/bin/jq"]
type = "file"
url = "https://github.com/stedolan/jq/releases/download/jq-{{ $jqVersion }}/jq-linux64"
refreshPeriod = "168h"
executable = true

{{ $pueueVersion := "3.2.0" }}
[".local/bin/pueue"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueueVersion }}/pueue-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $pueuedVersion := "3.2.0" }}
[".local/bin/pueued"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueuedVersion }}/pueued-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $moldVersion := "2.0.0" }}
[".local/bin/mold"]
type = "archive-file"
url = "https://github.com/rui314/mold/releases/download/v{{ $moldVersion }}/mold-{{ $moldVersion }}-x86_64-linux.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "bin/mold"

{{ $hadolintVersion := "2.12.0" }}
[".local/bin/hadolint"]
type = "file"
url = "https://github.com/hadolint/hadolint/releases/download/v{{ $hadolintVersion }}/hadolint-Linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $fnmVersion := "1.35.0" }}
[".local/bin/fnm"]
type = "archive-file"
url = "https://github.com/Schniz/fnm/releases/download/v{{ $fnmVersion }}/fnm-linux.zip"
refreshPeriod = "168h"
executable = true
path = "fnm"

{{ $fzfVersion := "0.42.0" }}
[".local/bin/fzf"]
type = "archive-file"
url = "https://github.com/junegunn/fzf/releases/download/{{ $fzfVersion }}/fzf-{{ $fzfVersion }}-linux_amd64.tar.gz"
refreshPeriod = "168h"
path = "fzf"

{{ $jjVersion := "0.8.0" }}
[".local/bin/jj"]
type = "archive-file"
url = "https://github.com/martinvonz/jj/releases/download/v{{ $jjVersion }}/jj-v{{ $jjVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
path = "./jj"

{{ $ryeVersion := "0.11.0" }}
[".local/bin/rye"]
type = "file"
url = "https://github.com/mitsuhiko/rye/releases/download/{{ $ryeVersion }}/rye-x86_64-linux.gz"
refreshPeriod = "168h"
executable = true
[".local/bin/rye".filter]
command = "gunzip"
args = ["--decompress", "--stdout"]

{{ $deltaVersion := "0.16.5" }}
[".local/bin/delta"]
type = "archive-file"
url = "https://github.com/dandavison/delta/releases/download/{{ $deltaVersion }}/delta-{{ $deltaVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
stripComponents = 1
path = "delta"

{{ $zimVersion := "1.12.0" }}
[".zim/zimfw.zsh"]
type = "file"
url = "https://github.com/zimfw/zimfw/releases/download/v{{ $zimVersion }}/zimfw.zsh"
refreshPeriod = "168h"

{{ $helixVersion := "23.05" }}
[".local/bin/hx"]
type = "archive-file"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 1
path = "hx"
[".config/helix/runtime"]
type = "archive"
url = "https://github.com/helix-editor/helix/releases/download/{{ $helixVersion }}/helix-{{ $helixVersion }}-x86_64-linux.tar.xz"
refreshPeriod = "168h"
stripComponents = 2
include = ["*/runtime/**"]

{{ end }}
