{{ $zimVersion := "1.14.0" }}
[".zim/zimfw.zsh"]
type = "file"
url = "https://github.com/zimfw/zimfw/releases/download/v{{ $zimVersion }}/zimfw.zsh"
refreshPeriod = "168h"

[".local/share/git-subrepo"]
type = "git-repo"
url = "https://github.com/ingydotnet/git-subrepo.git"
refreshPeriod = "168h"

{{ if eq .chezmoi.os "linux" }}

{{ $pueueVersion := "3.4.1" }}
[".local/bin/pueue"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueueVersion }}/pueue-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $pueuedVersion := "3.4.1" }}
[".local/bin/pueued"]
type = "file"
url = "https://github.com/Nukesor/pueue/releases/download/v{{ $pueuedVersion }}/pueued-linux-x86_64"
refreshPeriod = "168h"
executable = true

{{ $bazeliskVersion := "1.20.0" }}
[".local/bin/bazel"]
type = "file"
url = "https://github.com/bazelbuild/bazelisk/releases/download/v{{ $bazeliskVersion }}/bazelisk-linux-amd64"
refreshPeriod = "168h"
executable = true

# https://github.com/bazelbuild/buildtools/releases/download/v6.3.3/buildifier-linux-amd64
{{ $buildifierVersion := "7.3.1" }}
[".local/bin/buildifier"]
type = "file"
url = "https://github.com/bazelbuild/buildtools/releases/download/v{{ $buildifierVersion }}/buildifier-linux-amd64"
refreshPeriod = "168h"
executable = true

{{ $qvVersion := "0.8.4" }}
[".local/bin/qv"]
type = "archive-file"
url = "https://github.com/timvw/qv/releases/download/v{{ $qvVersion }}/qv-{{ $qvVersion }}-x86_64-unknown-linux-gnu-generic.tar.gz"
refreshPeriod = "168h"
path = "qv"

{{ end }}
