{{ if eq .chezmoi.os "linux" }}
{{ $lsdVersion := "0.23.1" }}
["local/bin/lsd"]
type = "file"
url = "https://github.com/Peltoche/lsd/releases/download/{{ $lsdVersion }}/lsd-{{ $lsdVersion }}-i686-unknown-linux-musl.tar.gz"
executable = true
["local/bin/lsd".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lsd-{{ $lsdVersion }}-i686-unknown-linux-musl/lsd"]
{{ end }}
