{{ if eq .chezmoi.os "linux" }}
{{ $lsdVersion := "0.23.1" }}
["local/bin/lsd"]
type = "file"
url = "https://github.com/Peltoche/lsd/releases/download/{{ $lsdVersion }}/lsd-{{ $lsdVersion }}-i686-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
executable = true
["local/bin/lsd".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "lsd-{{ $lsdVersion }}-i686-unknown-linux-musl/lsd"]

{{ $ghqVersion := "1.3.0" }}
["local/bin/ghq"]
type = "file"
url = "https://github.com/x-motemen/ghq/releases/download/v{{ $ghqVersion }}/ghq_linux_amd64.zip"
refreshPeriod = "168h"
executable = true
["local/bin/ghq".filter]
command = "bash"
args = ["-c", "tmpdir=$(mktemp -d); cat > $tmpdir/ghq_linux_amd64.zip && unzip -p $tmpdir/ghq_linux_amd64.zip ghq_linux_amd64/ghq"]

{{ $gitTownVersion := "7.8.0" }}
["local/bin/git-town"]
type = "file"
url = "https://github.com/git-town/git-town/releases/download/v{{ $gitTownVersion }}/git-town_{{ $gitTownVersion }}_linux_intel_64.tar.gz"
refreshPeriod = "168h"
executable = true
["local/bin/git-town".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "git-town"]

{{ $justVersion := "1.5.0" }}
["local/bin/just"]
type = "file"
url = "https://github.com/casey/just/releases/download/{{ $justVersion }}/just-{{ $justVersion }}-x86_64-unknown-linux-musl.tar.gz"
refreshPeriod = "168h"
executable = true
["local/bin/just".filter]
command = "tar"
args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "just"]
{{ end }}

[".fzf"]
type = "git-repo"
url = "https://github.com/junegunn/fzf"
refreshPeriod = "168h"
[".fzf".clone]
args = ["--depth", "1"]
