name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-ubuntu:
    strategy:
      matrix:
        image:
          # For the full list of images, see:
          # https://hub.docker.com/_/microsoft-vscode-devcontainers
          - mcr.microsoft.com/vscode/devcontainers/javascript-node:debian-10
          - mcr.microsoft.com/vscode/devcontainers/javascript-node:debian-11
          - mcr.microsoft.com/vscode/devcontainers/javascript-node:debian-12
          - mcr.microsoft.com/vscode/devcontainers/javascript-node:ubuntu-20.04
          - mcr.microsoft.com/vscode/devcontainers/javascript-node:ubuntu-21.04
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @bitwarden/cli
      - run: ./install.sh
        env:
          AQUA_GITHUB_TOKEN: ${{ secrets.AQUA_GITHUB_TOKEN }}
          BW_SESSION: ${{ secrets.BW_SESSION }}
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
  install-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @bitwarden/cli
      - run: ./install.sh
        env:
          AQUA_GITHUB_TOKEN: ${{ secrets.AQUA_GITHUB_TOKEN }}
          BW_SESSION: ${{ secrets.BW_SESSION }}
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
