name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @bitwarden/cli
      - run: echo "${{ secrets.BW_CLIENT_ID }}\n${{ secrets.BW_CLIENT_SECRET }}" | bw login --apikey
      - run: export BW_SESSION=$(echo ${{ secrets.BW_PASSWORD }} | bw login --raw) && ./install.sh
        env:
          AQUA_GITHUB_TOKEN: ${{ secrets.AQUA_GITHUB_TOKEN }}
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
