name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-ubuntu:
    strategy:
      matrix:
        image:
          # For the full list of images, see:
          # https://hub.docker.com/_/microsoft-vscode-devcontainers
          - mcr.microsoft.com/vscode/devcontainers/base:debian-11
          - mcr.microsoft.com/vscode/devcontainers/base:debian-12
          - mcr.microsoft.com/vscode/devcontainers/base:ubuntu-22.04
          - mcr.microsoft.com/vscode/devcontainers/base:ubuntu-24.04
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
        env:
          AQUA_GITHUB_TOKEN: ${{ secrets.AQUA_GITHUB_TOKEN }}
      - name: chezmoi doctor
        run: |
          git config --global --add safe.directory /__w/dotfiles/dotfiles
          mkdir -p /__w/dotfiles/.tmp
          export TMPDIR=/__w/dotfiles/.tmp
          "$HOME/.local/bin/chezmoi" doctor
  install-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./install.sh
        env:
          AQUA_GITHUB_TOKEN: ${{ secrets.AQUA_GITHUB_TOKEN }}
      - name: chezmoi doctor
        run: '"$HOME/.local/bin/chezmoi" doctor'
