name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    strategy:
      matrix:
        image:
          - mcr.microsoft.com/vscode/devcontainers/base:debian-10
          - mcr.microsoft.com/vscode/devcontainers/base:debian-11
          - mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
